#!/bin/bash
DIRECTORY="Source/AI"

if [ ! -d "$DIRECTORY" ]; then
    mkdir "$DIRECTORY"
else
    rm -rf "$DIRECTORY"
fi

cd Source
git clone https://github.com/Arktiks/Dalmuti-AI.git --quiet AI --depth=1 --branch=master

cd AI
rm -rf .git
rm .gitignore
