#!/bin/bash

echo Fetching AI repository.
./GET_AI
echo Done.

echo Compiling Dalmuti.
make --always-make
echo Done.

echo Playing Dalmuti.
./Dalmuti.out
echo Done.

echo Moving results.
mv Log.json Website/
echo Done.
